-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2025-05-07 20:38:02 EDT
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE client (
    id_client NUMBER NOT NULL,
    nom       VARCHAR2(255) NOT NULL,
    email     VARCHAR2(255) NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( id_client );

CREATE TABLE commande (
    id_commande        NUMBER NOT NULL,
    date_commande      DATE NOT NULL,
    quantite           INTEGER NOT NULL,
    prix               NUMBER NOT NULL,
    client_id_client   NUMBER NOT NULL,
    produit_id_produit NUMBER NOT NULL
);

ALTER TABLE commande ADD CONSTRAINT commande_pk PRIMARY KEY ( id_commande );

CREATE TABLE panier (
    id_panier            NUMBER NOT NULL,
    quantite             INTEGER NOT NULL,
    client_id_client     NUMBER NOT NULL,
    commande_id_commande NUMBER NOT NULL
);

CREATE UNIQUE INDEX panier__idx ON
    panier (
        client_id_client
    ASC );

ALTER TABLE panier ADD CONSTRAINT panier_pk PRIMARY KEY ( id_panier );

CREATE TABLE produit (
    id_produit    NUMBER NOT NULL,
    nom           unknown 
--  ERROR: Datatype UNKNOWN is not allowed 
     NOT NULL,
    taille        INTEGER NOT NULL,
    prix_unitaire NUMBER NOT NULL,
    stock         INTEGER NOT NULL,
    categorie     VARCHAR2(255) NOT NULL
);

ALTER TABLE produit ADD CONSTRAINT produit_pk PRIMARY KEY ( id_produit );

ALTER TABLE commande
    ADD CONSTRAINT commande_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );

ALTER TABLE commande
    ADD CONSTRAINT commande_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE panier
    ADD CONSTRAINT panier_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );

ALTER TABLE panier
    ADD CONSTRAINT panier_commande_fk FOREIGN KEY ( commande_id_commande )
        REFERENCES commande ( id_commande );

CREATE SEQUENCE client_id_client_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER client_id_client_trg BEFORE
    INSERT ON client
    FOR EACH ROW
    WHEN ( new.id_client IS NULL )
BEGIN
    :new.id_client := client_id_client_seq.nextval;
END;
/

CREATE SEQUENCE commande_id_commande_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER commande_id_commande_trg BEFORE
    INSERT ON commande
    FOR EACH ROW
    WHEN ( new.id_commande IS NULL )
BEGIN
    :new.id_commande := commande_id_commande_seq.nextval;
END;
/

CREATE SEQUENCE panier_id_panier_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER panier_id_panier_trg BEFORE
    INSERT ON panier
    FOR EACH ROW
    WHEN ( new.id_panier IS NULL )
BEGIN
    :new.id_panier := panier_id_panier_seq.nextval;
END;
/

CREATE SEQUENCE produit_id_produit_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER produit_id_produit_trg BEFORE
    INSERT ON produit
    FOR EACH ROW
    WHEN ( new.id_produit IS NULL )
BEGIN
    :new.id_produit := produit_id_produit_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             4
-- CREATE INDEX                             1
-- ALTER TABLE                              8
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           4
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
